/**
 * Mock data for Race to Turin rankings.
 * Placeholder data for UI development — will be replaced by real scraping data.
 */

import type { RaceRankingEntry, RaceSummary } from "@/types";

/** Summary data for the Race overview cards */
export const MOCK_RACE_SUMMARY: RaceSummary = {
  qualifiedCount: 4,
  totalSlots: 8,
  qualifiedNames: ["Sinner", "Alcaraz", "Zverev", "Medvedev"],
  remainingTournaments: 1,
  nextTournament: "Paris Masters (Next Week)",
  cutoffPoints: "~3500 pts",
};

/** Mock Race to Turin ranking entries */
export const MOCK_RACE_RANKINGS: RaceRankingEntry[] = [
  {
    rank: 1,
    player: { id: "sinner", name: "Jannik Sinner", nationality: "ITA", countryCode: "it", age: 24, initials: "JS" },
    points: 10330,
    liveStatus: { isActive: false, tournament: "Roland Garros", stage: "R64" },
    movement: { type: "none" },
    officialPoints: 10330,
    pointsDiff: 0,
    nextMatchPoints: 10330,
    maxPoints: 10330,
    bestRanking: 1,
    raceStatus: "qualified",
  },
  {
    rank: 2,
    player: { id: "alcaraz", name: "Carlos Alcaraz", nationality: "ESP", countryCode: "es", age: 23, initials: "CA" },
    points: 6710,
    liveStatus: { isActive: false, tournament: "Roland Garros", stage: "R64" },
    movement: { type: "none" },
    officialPoints: 6710,
    pointsDiff: 0,
    nextMatchPoints: 6710,
    maxPoints: 6710,
    bestRanking: 1,
    raceStatus: "qualified",
  },
  {
    rank: 3,
    player: { id: "zverev", name: "Alexander Zverev", nationality: "GER", countryCode: "de", age: 29, initials: "AZ" },
    points: 6215,
    liveStatus: { isActive: true, tournament: "Roland Garros", stage: "SF" },
    movement: { type: "up", value: 1 },
    officialPoints: 5815,
    pointsDiff: 400,
    nextMatchPoints: 6715,
    maxPoints: 7415,
    bestRanking: 2,
    raceStatus: "qualified",
  },
  {
    rank: 4,
    player: { id: "medvedev", name: "Daniil Medvedev", nationality: "RUS", countryCode: "ru", age: 30, initials: "DM" },
    points: 4820,
    liveStatus: { isActive: false, tournament: "Roland Garros", stage: "R128" },
    movement: { type: "down", value: 1 },
    officialPoints: 4820,
    pointsDiff: 0,
    nextMatchPoints: 4820,
    maxPoints: 4820,
    bestRanking: 1,
    raceStatus: "qualified",
  },
  {
    rank: 5,
    player: { id: "fritz", name: "Taylor Fritz", nationality: "USA", countryCode: "us", age: 27, initials: "TF" },
    points: 4290,
    liveStatus: { isActive: false, tournament: "Roland Garros", stage: "R16" },
    movement: { type: "none" },
    officialPoints: 4290,
    pointsDiff: 0,
    nextMatchPoints: 4290,
    maxPoints: 4290,
    bestRanking: 4,
    raceStatus: "in-contention",
  },
  {
    rank: 6,
    player: { id: "djokovic", name: "Novak Djokovic", nationality: "SRB", countryCode: "rs", age: 39, initials: "ND" },
    points: 3910,
    liveStatus: { isActive: false, tournament: "Roland Garros", stage: "R32" },
    movement: { type: "none" },
    officialPoints: 3910,
    pointsDiff: 0,
    nextMatchPoints: 3910,
    maxPoints: 3910,
    bestRanking: 1,
    raceStatus: "in-contention",
  },
  {
    rank: 7,
    player: { id: "ruud", name: "Casper Ruud", nationality: "NOR", countryCode: "no", age: 26, initials: "CR" },
    points: 3645,
    liveStatus: { isActive: true, tournament: "Roland Garros", stage: "QF" },
    movement: { type: "up", value: 2 },
    officialPoints: 3245,
    pointsDiff: 400,
    nextMatchPoints: 4045,
    maxPoints: 4745,
    bestRanking: 2,
    raceStatus: "in-contention",
  },
  {
    rank: 8,
    player: { id: "shelton", name: "Ben Shelton", nationality: "USA", countryCode: "us", age: 23, initials: "BS" },
    points: 3520,
    liveStatus: { isActive: false, tournament: "Roland Garros", stage: "R64" },
    movement: { type: "mr" },
    officialPoints: 3520,
    pointsDiff: 0,
    nextMatchPoints: 3520,
    maxPoints: 3520,
    bestRanking: 5,
    raceStatus: "in-contention",
  },
  // --- Below the qualification cut ---
  {
    rank: 9,
    player: { id: "rune", name: "Holger Rune", nationality: "DEN", countryCode: "dk", age: 22, initials: "HR" },
    points: 3340,
    liveStatus: { isActive: true, tournament: "Roland Garros", stage: "QF" },
    movement: { type: "up", value: 3 },
    officialPoints: 2940,
    pointsDiff: 400,
    nextMatchPoints: 3740,
    maxPoints: 4440,
    bestRanking: 4,
    raceStatus: "in-contention",
  },
  {
    rank: 10,
    player: { id: "draper", name: "Jack Draper", nationality: "GBR", countryCode: "gb", age: 23, initials: "JD" },
    points: 3180,
    liveStatus: { isActive: false, tournament: "Roland Garros", stage: "R32" },
    movement: { type: "none" },
    officialPoints: 3180,
    pointsDiff: 0,
    nextMatchPoints: 3180,
    maxPoints: 3180,
    bestRanking: 11,
    raceStatus: "in-contention",
  },
  {
    rank: 11,
    player: { id: "auger", name: "Félix Auger-Aliassime", nationality: "CAN", countryCode: "ca", age: 25, initials: "FA" },
    points: 2980,
    liveStatus: { isActive: true, tournament: "Roland Garros", stage: "QF" },
    movement: { type: "up", value: 2 },
    officialPoints: 2580,
    pointsDiff: 400,
    nextMatchPoints: 3380,
    maxPoints: 4080,
    bestRanking: 6,
    raceStatus: "in-contention",
  },
  {
    rank: 12,
    player: { id: "tsitsipas", name: "Stefanos Tsitsipas", nationality: "GRE", countryCode: "gr", age: 26, initials: "ST" },
    points: 2750,
    liveStatus: { isActive: false, tournament: "Roland Garros", stage: "R16" },
    movement: { type: "down", value: 2 },
    officialPoints: 2750,
    pointsDiff: 0,
    nextMatchPoints: 2750,
    maxPoints: 2750,
    bestRanking: 3,
    raceStatus: "in-contention",
  },
  {
    rank: 13,
    player: { id: "deminaur", name: "Alex de Minaur", nationality: "AUS", countryCode: "au", age: 27, initials: "AD" },
    points: 2620,
    liveStatus: { isActive: false, tournament: "Roland Garros", stage: "R32" },
    movement: { type: "up", value: 1 },
    officialPoints: 2570,
    pointsDiff: 50,
    nextMatchPoints: 2620,
    maxPoints: 2620,
    bestRanking: 6,
    raceStatus: "in-contention",
  },
  {
    rank: 14,
    player: { id: "paul", name: "Tommy Paul", nationality: "USA", countryCode: "us", age: 27, initials: "TP" },
    points: 2490,
    liveStatus: { isActive: false, tournament: "Roland Garros", stage: "R64" },
    movement: { type: "none" },
    officialPoints: 2490,
    pointsDiff: 0,
    nextMatchPoints: 2490,
    maxPoints: 2490,
    bestRanking: 10,
    raceStatus: "in-contention",
  },
  {
    rank: 15,
    player: { id: "musetti", name: "Lorenzo Musetti", nationality: "ITA", countryCode: "it", age: 23, initials: "LM" },
    points: 2320,
    liveStatus: { isActive: true, tournament: "Roland Garros", stage: "QF" },
    movement: { type: "up", value: 4 },
    officialPoints: 1920,
    pointsDiff: 400,
    nextMatchPoints: 2720,
    maxPoints: 3420,
    bestRanking: 15,
    raceStatus: "in-contention",
  },
];
